# Generated by Django 4.0.6 on 2022-08-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QRcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('date_created', models.TimeField()),
                ('base_url', models.TextField()),
                ('type_qr', models.TextField()),
                ('stats', models.IntegerField()),
            ],
        ),
    ]
