# Generated by Django 4.0.6 on 2022-08-04 18:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('qr_gen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='owner',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
