# Generated by Django 4.0.6 on 2022-08-13 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_gen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='qrcode',
            field=models.ImageField(upload_to='media'),
        ),
    ]
