# Generated by Django 4.0.6 on 2022-08-10 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_gen', '0002_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='qrcode',
            field=models.ImageField(default=1, upload_to='static/qrcodes/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='owner',
            name='total_active',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='owner',
            name='total_qr',
            field=models.IntegerField(default=1),
        ),
    ]
