# Generated by Django 4.0.6 on 2022-08-04 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_gen', '0002_qrcode_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='date_created',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='owner',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
