# Generated by Django 4.0.6 on 2022-08-15 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_gen', '0002_alter_qrcode_qrcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRcodeEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('owner', models.CharField(max_length=50)),
                ('date_created', models.DateField(auto_now=True)),
                ('to', models.TextField()),
                ('subject', models.TextField()),
                ('body', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('light', models.CharField(default='white', max_length=15)),
                ('dark', models.CharField(default='black', max_length=15)),
                ('stats', models.IntegerField(default=0)),
                ('qrcode', models.ImageField(upload_to='media')),
                ('type_qr', models.TextField(default='Location')),
                ('tag', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='QRcodeLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('owner', models.CharField(max_length=50)),
                ('date_created', models.DateField(auto_now=True)),
                ('long', models.TextField()),
                ('lat', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('light', models.CharField(default='white', max_length=15)),
                ('dark', models.CharField(default='black', max_length=15)),
                ('stats', models.IntegerField(default=0)),
                ('qrcode', models.ImageField(upload_to='media')),
                ('type_qr', models.TextField(default='Location')),
                ('tag', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='QRcodeWifi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('owner', models.CharField(max_length=50)),
                ('date_created', models.DateField(auto_now=True)),
                ('ssid', models.TextField()),
                ('password', models.TextField()),
                ('security', models.CharField(max_length=6)),
                ('active', models.BooleanField(default=True)),
                ('light', models.CharField(default='white', max_length=15)),
                ('dark', models.CharField(default='black', max_length=15)),
                ('stats', models.IntegerField(default=0)),
                ('qrcode', models.ImageField(upload_to='media')),
                ('type_qr', models.TextField(default='Wifi')),
                ('tag', models.TextField()),
            ],
        ),
    ]
