# Generated by Django 4.0.6 on 2022-08-10 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_gen', '0003_qrcode_qrcode_alter_owner_total_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='qrcode',
            field=models.ImageField(upload_to='qr_gen/static/qrcodes/'),
        ),
    ]
