# Generated by Django 4.0.6 on 2022-08-05 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_gen', '0004_alter_qrcode_stats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='date_created',
            field=models.DateField(auto_now=True),
        ),
    ]
