# Generated by Django 4.0.6 on 2022-08-11 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_gen', '0004_alter_qrcode_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='tag',
            field=models.TextField(default=1010),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='qrcode',
            field=models.ImageField(upload_to='static/qrcodes/'),
        ),
    ]
